In [1]:
import xgboost as xgb
import numpy as np
import pickle
from joblib import dump, load
import pandas as pd

In [ ]:
# I have binned the age column. So age 0-10 is 0, 10-20 is 10, 20-30 is 20 and so on. The binned values are integers.

In [2]:
# col_list=['Number of sexual partners',
#  'Num of pregnancies',
#  'Smokes',
#  'Hormonal Contraceptives',
#  'STDs:vulvo-perineal condylomatosis',
#  'STDs:genital herpes',
#  'STDs:HIV',
#  'Hinselmann',
#  'Schiller',
#  'Citology',
#  'Age_bin',
#  'Biopsy']

# These are the features.
model = xgb.XGBClassifier() ## To use a different model just check the sklearn documentation

model = load('xgb.joblib') 
    
def inference(model,features):
    # features must be a numpy array of dimension (n_samples,feature_length). In our case feature length is 11. Must follow the exact order given in col_list 
    prediction = model.predict(features)
    

    return prediction

In [3]:
df = pd.read_csv("final_data.csv")

In [4]:
col_list=['Number of sexual partners',
 'Num of pregnancies',
 'Smokes',
 'Hormonal Contraceptives',
 'STDs:vulvo-perineal condylomatosis',
 'STDs:genital herpes',
 'STDs:HIV',
 'Hinselmann',
 'Schiller',
 'Citology',
 'Age_bin',
 'Biopsy']

pruned_df = df[col_list]

In [5]:
X = pruned_df.drop(["Biopsy"],axis=1)
y = pruned_df["Biopsy"]

In [6]:
X_numpy = X.to_numpy()

In [15]:
X_numpy 

array([[ 4.,  1.,  0., ...,  0.,  0., 10.],
       [ 1.,  1.,  0., ...,  0.,  0., 10.],
       [ 5.,  4.,  1., ...,  0.,  0., 50.],
       ...,
       [ 2.,  0.,  0., ...,  0.,  1., 20.],
       [ 2.,  2.,  0., ...,  0.,  0., 30.],
       [ 2.,  1.,  0., ...,  0.,  0., 20.]])

In [7]:
X_numpy[0]

array([ 4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.])

In [20]:
X_numpy[5]

array([ 3.,  6.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0., 50.])

In [27]:
inference(model,X_numpy[:5])

array([0, 0, 0, 0, 0])